config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

 

  resources :products do
    resources :reviews, :only => [:show, :create, :destroy]
  end

  resources :products
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create]
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	has_many :users, :through => :reviews

	validates :description, :name, :presence => true
	validates :price, :numericality => [:only_integer => :true]
end

app/models/reviews.rb
class Reviews < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many :reviews
	has_many :products, :through => :reviews

	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 	def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
 	 
    private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :ensure_logged_in, :only => [:create]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
    if current_user
      @review = @product.review.build
    end
  end

  def update
    @product = Product.find(params[:id])
    @product.update_atrributes(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.delete
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_filter = :ensure_logged_in, :only => [:create, :edit, :show, :update, :destroy]
	before_filter :load_product

  def show
  	@product = Product.find[params[:id]]

  end

  def create
  	@product = Product.find(params[:product_id])
  	@review = @product.review.build(review_params)
  	@review.user_id = current_user.id
  	if @review.save
  		redirect_to products_path, :notice => "Review Created!"
  	else
  		render "new"
  	end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private

  def review_params
  	params.require(:review).permit(:product_id, :create, :comment)
	end

	def load_product
		@product = Product.find(:product_id)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice => "Logged In"
  	else
  		flash.now[:alert] = "Invalid username or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, :notice => "logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url, :notice => "Siggned In"
  	else
  		render :new
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rforest5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1> Products </h1>

<div>
<%= link_to "Create a Product", new_product_path %>
</div>

<div>
	<%= link_to "Log In", new_session_path %>
</div>

<% @products.each do |product| %>
	<p> <%= link_to image_tag(product), product_url(product.id) %></p>
<% end %>

app/views/products/new.html.erb
<h1> Create a new Product </h1>
<%= form_for(@product) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= form_for(@product) do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

	<ul>
		<%@product.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<%end%>
	</ul>
</div>
<%end%>
<%end%>

app/views/products/show.html.erb
<%= link_to "Back", products_path %>
<p><%= @product.name %>, <%= @product.description %>, <%= @product.price %></p>

<% if current_user %>

<h3> Reviews </h3>

<p> Reviews for <%= @producr.name %></p>
<% @product.reviews.each do |review| %>
<p>
	<%= review.comment %><br>
	<% if review.user != nil %>
	<em> by <%= review.user.email %></em>
	Added on: <%= review.created_at %>
	<%end%>
</p>
<%end%>


	<h4> New Review</h4>

	<%= form_for [(@product, @review)] %>
		<% if @review.errors.any? %>
		<div class"error.explanation" >
			<h2><%= pluralize(@review.error.count, "error") %> prohibbit this review from being saved:</h2>
			<li>
				<%msg%>
			</li>
			<%end%>
		</ul>
	</div>
	<%end%>

  

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="actions"><%= f.submit %></div>
<% end %>